name: Deploy Lambda Function

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      user_id:
        description: 'ID of the user'
        required: true
      instance_id:
        description: 'ID of the instance'
        required: true
      instance_type:
        description: 'Type of instance: google_drive or s3'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        id: apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve -var "user_id=${{ github.event.inputs.user_id }}" -var "instance_id=${{ github.event.inputs.instance_id }}" -var "instance_type=${{ github.event.inputs.instance_type }}"

      - name: Output Results
        run: |
          echo "Function Status: $(terraform output function_status)"
          echo "Lambda Function Name: $(terraform output lambda_function_name)"
        id: output
